version: '3.5'

services:
  employees-db:
    image: postgres
    container_name: hibernate_demo-db
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=user
      - POSTGRES_DB=hibernate_demo
    ports:
      - "5544:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data