create table person
(
    id   int primary key generated by default as identity,
    name varchar(100) not null ,
    age  int check ( age < 100 )
);

insert into person (name, age)
values ('Test1', 18),
       ('Test2', 20),
       ('Test3', 50);

create table item
(
    id   int primary key generated by default as identity,
    person_id int references person(id) on delete set null,
    item_name varchar(100) not null
);

insert into item (person_id, item_name)
values (1, 'prod1'),
       (1, 'prod2'),
       (2, 'prod3'),
       (3, 'prod4'),
       (3, 'prod5'),
       (3, 'prod6');


create table passport
(
    id int primary key generated by default as identity,
    person_id   int unique references person(id) on delete cascade,
    passport_number  int not null
);

------------------
--10. Отношение Многие ко Многим (Many-to-Many) в Hibernate
create table actor
(
    id int primary key generated by default as identity,
    name varchar(100) not null unique,
    age int check ( age > 0 )
);

create table movie
(
    id int primary key generated by default as identity,
    name varchar(200) not null,
    year_of_production int check ( year_of_production > 1900 )
);

create table actor_movie
(
    actor_id int references actor(id),
    movie_id int references movie(id),
    primary key (actor_id, movie_id)
);